<?xml version="1.0"?>
<robot name = "robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find description)/urdf/properties.xacro"/>
    <xacro:include filename="$(find description)/urdf/chassis.xacro"/>
    <xacro:include filename="$(find description)/urdf/wheel.xacro"/>
    
    <xacro:chassis update_rate="40"/>
    <xacro:wheel 
        name="left" 
        translation="0 ${WHEEL_SEPARATION / 2} 0" 
        rotation="0 0 0" 
        parent="base_link"/>

    <xacro:wheel 
        name="right" 
        translation="0 ${-WHEEL_SEPARATION / 2} 0" 
        rotation="0 0 0" 
        parent="base_link"/>

</robot>