my_robot:
  joint_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 0.6, i: 6, d: 0.0}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 0.6, i: 6, d: 0.0}